name: Jekyll Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Jekyll Site using Docker
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/srv/jekyll" \
            -w /srv/jekyll \
            jekyll/jekyll:latest \
            jekyll build

      - name: Upload built site as artifact
        uses: actions/upload-artifact@v2
        with:
          name: jekyll-site
          path: _site
